package Model;

public interface Constants {
    int N_NAIPE=4;
    int TIPO_CARTA=13;
    TYPE [] types = {TYPE.PAUS, TYPE.ESPADAS, TYPE.COPAS, TYPE.OUROS};
    int [] val= {2,3,4,5,6,7,8,9,10,10,10,10,11};

    FIGURE [] figures ={FIGURE.NUM2, FIGURE.NUM3,FIGURE.NUM4,FIGURE.NUM5,FIGURE.NUM6,FIGURE.NUM7,
    FIGURE.NUM8,FIGURE.NUM9,FIGURE.NUM10,FIGURE.AS,FIGURE.VALETE,FIGURE.REI,FIGURE.DAMA};
}
